DROP TYPE IF EXISTS vinculo CASCADE;
CREATE TYPE vinculo AS ENUM (
  'aluno',
  'professor',
  'funcionario_publico'
);

DROP TYPE IF EXISTS nivel_ensino_curso CASCADE;
CREATE TYPE nivel_ensino_curso AS ENUM (
  'fundamental',
  'medio',
  'tecnico',
  'graduacao'
);

DROP TYPE IF EXISTS titulacao_professor CASCADE;
CREATE TYPE titulacao_professor AS ENUM (
  'pos_doutorado',
  'doutorado',
  'mestrado'
);

DROP TYPE IF EXISTS status_matricula CASCADE;
CREATE TYPE status_matricula AS ENUM (
  'pendente',
  'ativo',
  'trancado',
  'concluido',
  'reprovado'
);

DROP TYPE IF EXISTS status_pagamento_matricula CASCADE;
CREATE TYPE status_pagamento_matricula AS ENUM (
  'pendente',
  'pago'
);

DROP TABLE IF EXISTS unidade_escola CASCADE;
CREATE TABLE unidade_escola (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade varchar NOT NULL,
  estado varchar NOT NULL,
  pais varchar NOT NULL,
  predio_bloco varchar
);

DROP TABLE IF EXISTS regra CASCADE;
CREATE TABLE regra (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao text
);

DROP TABLE IF EXISTS infraestrutura CASCADE;
CREATE TABLE infraestrutura (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao text
);

DROP TABLE IF EXISTS bolsa CASCADE;
CREATE TABLE bolsa (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar NOT NULL,
  valor float NOT NULL
);

DROP TABLE IF EXISTS usuario CASCADE;
CREATE TABLE usuario (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  sobrenome varchar NOT NULL,
  numero_telefone varchar NOT NULL,
  dia_nascimento int NOT NULL,
  mes_nascimento int NOT NULL,
  ano_nascimento int NOT NULL,
  rua varchar NOT NULL,
  numero varchar NOT NULL,
  cep varchar NOT NULL,
  cidade varchar NOT NULL,
  sexo varchar NOT NULL,
  email varchar NOT NULL,
  senha varchar NOT NULL,
  area_especializacao varchar,
  titulacao titulacao_professor,
  id_unidade_escola int,

  UNIQUE (nome, sobrenome, numero_telefone),
  FOREIGN KEY (id_unidade_escola) REFERENCES unidade_escola (id)
);

DROP TABLE IF EXISTS vinculo_usuario CASCADE;
CREATE TABLE vinculo_usuario (
  id_usuario int,
  vinculo vinculo,

  FOREIGN KEY (id_usuario) REFERENCES usuario (id)
);

DROP TABLE IF EXISTS disciplina CASCADE;
CREATE TABLE disciplina (
  codigo varchar PRIMARY KEY,
  nome varchar NOT NULL,
  n_aulas_semanais int NOT NULL,
  id_unidade_escola int NOT NULL,

  FOREIGN KEY (id_unidade_escola) REFERENCES unidade_escola (id)
);

DROP TABLE IF EXISTS sala CASCADE;
CREATE TABLE sala (
  codigo varchar PRIMARY KEY,
  capacidade int NOT NULL
);

DROP TABLE IF EXISTS oferta CASCADE;
CREATE TABLE oferta (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano int NOT NULL,
  semestre int NOT NULL,
  codigo_sala varchar,
  codigo_disciplina varchar NOT NULL,

  FOREIGN KEY (codigo_disciplina) REFERENCES disciplina (codigo),
  FOREIGN KEY (codigo_sala) REFERENCES sala (codigo)
);

DROP TABLE IF EXISTS matricula CASCADE;
CREATE TABLE matricula (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_aluno int NOT NULL,
  id_oferta int NOT NULL,
  dia_efetivacao int,
  mes_efetivacao int,
  ano_efetivacao int,
  status status_matricula NOT NULL,
  status_pagamento status_pagamento_matricula,
  dia_limite_confirmacao int NOT NULL,
  mes_limite_confirmacao int NOT NULL,
  ano_limite_confirmacao int NOT NULL,

  FOREIGN KEY (id_aluno) REFERENCES usuario (id),
  FOREIGN KEY (id_oferta) REFERENCES oferta (id)
);

DROP TABLE IF EXISTS avaliacao_professor CASCADE;
CREATE TABLE avaliacao_professor (
  nome_disciplina     varchar NOT NULL,
  id_professor        int     NOT NULL,
  id_aluno            int     NOT NULL,
  didatica_nota            decimal(3,1) NOT NULL
    CHECK (didatica_nota BETWEEN 0.0 AND 10.0),
  PRIMARY KEY (nome_disciplina, id_aluno, id_professor),
  FOREIGN KEY (id_aluno)     REFERENCES usuario (id),
  FOREIGN KEY (id_professor) REFERENCES usuario (id)
);

DROP TABLE IF EXISTS avaliacao_disciplina CASCADE;
CREATE TABLE avaliacao_disciplina (
  id_aluno             int     NOT NULL,
  codigo_disciplina    varchar NOT NULL,
  comentario_texto     text,
  material_apoio_nota       decimal(3,1) NOT NULL
    CHECK (material_apoio_nota BETWEEN 0.0 AND 10.0),
  infraestrutura_sala_nota  decimal(3,1) NOT NULL
    CHECK (infraestrutura_sala_nota BETWEEN 0.0 AND 10.0),
  relevancia_conteudo_nota  decimal(3,1) NOT NULL
    CHECK (relevancia_conteudo_nota BETWEEN 0.0 AND 10.0),
  PRIMARY KEY (id_aluno, codigo_disciplina),
  FOREIGN KEY (codigo_disciplina) REFERENCES disciplina (codigo),
  FOREIGN KEY (id_aluno)          REFERENCES usuario (id)
);


DROP TABLE IF EXISTS departamento_academico CASCADE;
CREATE TABLE departamento_academico (
  codigo varchar PRIMARY KEY,
  nome varchar NOT NULL,
  id_professor_chefe int NOT NULL,

  FOREIGN KEY (id_professor_chefe) REFERENCES usuario (id)
);

DROP TABLE IF EXISTS curso CASCADE;
CREATE TABLE curso (
  codigo varchar PRIMARY KEY,
  nome varchar NOT NULL,
  nivel_ensino nivel_ensino_curso NOT NULL,
  carga_horaria_total int NOT NULL,
  numero_vagas int NOT NULL,
  ementa text,
  codigo_padrao varchar,
  codigo_departamento_academico varchar NOT NULL,
  id_unidade_escola int NOT NULL,

  FOREIGN KEY (id_unidade_escola) REFERENCES unidade_escola (id),
  FOREIGN KEY (codigo_departamento_academico) REFERENCES departamento_academico (codigo),
  FOREIGN KEY (codigo_padrao) REFERENCES sala (codigo)
);

DROP TABLE IF EXISTS aviso CASCADE;
CREATE TABLE aviso (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texto_mensagem text NOT NULL,
  dia_criacao int NOT NULL,
  mes_criacao int NOT NULL,
  ano_criacao int NOT NULL,
  hora_criacao time NOT NULL,
  id_funcionario_administrativo int NOT NULL,

  FOREIGN KEY (id_funcionario_administrativo) REFERENCES usuario (id)
);

DROP TABLE IF EXISTS mensagem CASCADE;
CREATE TABLE mensagem (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texto_mensagem text NOT NULL,
  dia_criacao int NOT NULL,
  mes_criacao int NOT NULL,
  ano_criacao int NOT NULL,
  hora_criacao time NOT NULL,
  id_usuario int NOT NULL,

  FOREIGN KEY (id_usuario) REFERENCES usuario (id)
);

DROP TABLE IF EXISTS prerequisito_curso_curso CASCADE;
CREATE TABLE prerequisito_curso_curso (
  codigo_curso varchar,
  codigo_curso_prerequisito varchar,
  PRIMARY KEY (codigo_curso, codigo_curso_prerequisito),

  FOREIGN KEY (codigo_curso) REFERENCES curso (codigo),
  FOREIGN KEY (codigo_curso_prerequisito) REFERENCES curso (codigo)
);

DROP TABLE IF EXISTS prerequisito_disciplina_curso CASCADE;
CREATE TABLE prerequisito_disciplina_curso (
  codigo_curso varchar,
  codigo_disciplina_prerequisito varchar,
  PRIMARY KEY (codigo_curso, codigo_disciplina_prerequisito),

  FOREIGN KEY (codigo_disciplina_prerequisito) REFERENCES disciplina (codigo),
  FOREIGN KEY (codigo_curso) REFERENCES curso (codigo)
);

DROP TABLE IF EXISTS regra_curso CASCADE;
CREATE TABLE regra_curso (
  codigo_curso varchar,
  id_regra int,
  PRIMARY KEY (codigo_curso, id_regra),

  FOREIGN KEY (codigo_curso) REFERENCES curso (codigo),
  FOREIGN KEY (id_regra) REFERENCES regra (id)
);

DROP TABLE IF EXISTS infraestrutura_curso CASCADE;
CREATE TABLE infraestrutura_curso (
  codigo_curso varchar,
  id_infraestrutura int,
  PRIMARY KEY (codigo_curso, id_infraestrutura),

  FOREIGN KEY (codigo_curso) REFERENCES curso (codigo),
  FOREIGN KEY (id_infraestrutura) REFERENCES infraestrutura (id)
);

DROP TABLE IF EXISTS disciplina_curso CASCADE;
CREATE TABLE disciplina_curso (
  codigo_curso varchar,
  codigo_disciplina varchar,
  PRIMARY KEY (codigo_curso, codigo_disciplina),

  FOREIGN KEY (codigo_disciplina) REFERENCES disciplina (codigo),
  FOREIGN KEY (codigo_curso) REFERENCES curso (codigo)
);

DROP TABLE IF EXISTS responsavel_disciplina CASCADE;
CREATE TABLE responsavel_disciplina (
  codigo_disciplina varchar,
  id_professor int,
  PRIMARY KEY (codigo_disciplina, id_professor),

  FOREIGN KEY (codigo_disciplina) REFERENCES disciplina (codigo),
  FOREIGN KEY (id_professor) REFERENCES usuario (id)
);

DROP TABLE IF EXISTS matricula_bolsa CASCADE;
CREATE TABLE matricula_bolsa (
  id_matricula int,
  id_bolsa int,
  dia_inicio int NOT NULL,
  mes_inicio int NOT NULL,
  ano_inicio int NOT NULL,
  dia_prazo_validade int NOT NULL,
  mes_prazo_validade int NOT NULL,
  ano_prazo_validade int NOT NULL,
  PRIMARY KEY (id_matricula, id_bolsa),

  FOREIGN KEY (id_bolsa) REFERENCES bolsa (id),
  FOREIGN KEY (id_matricula) REFERENCES matricula (id)
);

DROP TABLE IF EXISTS material_didatico CASCADE;
CREATE TABLE material_didatico (
  codigo_disciplina varchar,
  titulo text,
  PRIMARY KEY (codigo_disciplina, titulo),

  FOREIGN KEY (codigo_disciplina) REFERENCES disciplina (codigo)
);

DROP TABLE IF EXISTS nota CASCADE;
CREATE TABLE nota (
  id_matricula int,
  motivo text,
  valor decimal,
  PRIMARY KEY (id_matricula, motivo),

  FOREIGN KEY (id_matricula) REFERENCES matricula (id)
);

DROP TABLE IF EXISTS desconto CASCADE;
CREATE TABLE desconto (
  id_matricula int,
  motivo text,
  valor decimal,
  PRIMARY KEY (id_matricula, motivo),

  FOREIGN KEY (id_matricula) REFERENCES matricula (id)
);

DROP TABLE IF EXISTS taxa CASCADE;
CREATE TABLE taxa (
  id_matricula int,
  motivo text,
  valor decimal,
  PRIMARY KEY (id_matricula, motivo),

  FOREIGN KEY (id_matricula) REFERENCES matricula (id)
);

DROP TABLE IF EXISTS destinatario CASCADE;
CREATE TABLE destinatario (
  id_mensagem int,
  id_destinatario int,
  PRIMARY KEY (id_mensagem, id_destinatario),

  FOREIGN KEY (id_destinatario) REFERENCES usuario (id),
  FOREIGN KEY (id_mensagem) REFERENCES mensagem (id)
);